# Generated by Django 4.2.23 on 2025-08-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
