# Generated by Django 4.2.23 on 2025-08-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_tenant_api_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryStatus',
        ),
    ]
